---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rollfxnz/public_html/
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R JS_css $DEPLOYPATH
    - /bin/cp -R PHP $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH